server:
  port: 8082
mongodb:
  host: mongodbIP
  port: 8074
  name: dbname
spring:
  datasource:
    name: dbname
    username: username
    password: XXXXXXX
    url: jdbc:mysql://47.93.54.230:3306/collage?useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20   